name: Pipeline

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Run o dev
        run: echo COÉ TA NO DEV
  deploy-hmg:
    runs-on: ubuntu-latest
    environment: HMG
    steps:
      - name: Checkout
        run: git checkout main
      - name: Check status
        run: git status
      - name: Create release
        run: git branch release-20230201-1200
      - name: Checkout to release
        run: git checkout release-20230201-1200
      - name: Merge to release
        run: git merge feature/pipeline-2
  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout
        run: git checkout main
      - name: Merge
        run: git merge release-20230201-1200
