name: Pipeline

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Clone
        run: git clone https://github.com/KaykyDeSouzaDias/pipeline-template.git
      - name: CD
        run: cd pipeline-template
      - name: Initialize
        run: git init
      - name: Fetch
        run: git fetch
      - name: Check status
        run: git status
  deploy-hmg:
    runs-on: ubuntu-latest
    environment: HMG
    steps:
      - name: Clone
        run: git clone https://github.com/KaykyDeSouzaDias/pipeline-template.git
      - name: CD
        run: cd pipeline-template
      - name: Initialize
        run: git init
      - name: Fetch
        run: git fetch
      - name: Checkout
        run: git checkout master
      - name: Create release
        run: git branch release-20230201-1200
      - name: Checkout to release
        run: git checkout release-20230201-1200
      - name: Merge to release
        run: git merge feature/pipeline-2
  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Clone
        run: git clone https://github.com/KaykyDeSouzaDias/pipeline-template.git
      - name: CD
        run: cd pipeline-template
      - name: Initialize
        run: git init
      - name: Fetch
        run: git fetch
      - name: Checkout
        run: git checkout master
      - name: Merge
        run: git merge release-20230201-1200
