name: Pipeline

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3
      - name: Repository file list
        run: ls
      - name: Fetch
        run: git fetch --all
      - name: Branch all
        run: git branch -a
      - name: Check status
        run: git status
  deploy-hmg:
    runs-on: ubuntu-latest
    environment: HMG
    steps:
    - uses: actions/checkout@v2
    - name: Approval
      run: |
          git fetch
          git pull
          git branch release-20230201-1200
          git branch -a
          git checkout feature/pipeline-2
          git branch -a
          git checkout release-20230201-1200
          git branch -a
          git merge --allow-unrelated-histories origin/feature/pipeline-2
          git push
  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch
        run: git fetch --all
      - name: Merge
        run: git merge release-20230201-1200
